name: Android CI Post Merge Check
# Run extra build and checks to ensure `main` is functioning right.

on:
  push:
    branches: [ "main" ]

jobs:
  android-post-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Linter
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build

      # https://github.com/marketplace/actions/cache
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
