# danger-kotlin
# https://github.com/marketplace/actions/danger-kotlin
name: "Run Danger"

on:
  pull_request:
    branches:
      - main
# Disabled danger on `main` because of following error after mering to `main`
# kotlinx.serialization.MissingFieldException: Fields [issue, pr, commits, reviews, requested_reviewers] are required 
# for type with serial name 'systems.danger.kotlin.models.github.GitHub', but they were missing
  # push:
  #   branches:
  #     - main

jobs:
  danger-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/kotlin@1.3.1
        env:
          # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
